# permissions for end users to edit ovnkubeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovnkubeconfig-editor-role
rules:
- apiGroups:
  - dpu.openshift.io
  resources:
  - ovnkubeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dpu.openshift.io
  resources:
  - ovnkubeconfigs/status
  verbs:
  - get
