# permissions for end users to view ovnkubeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovnkubeconfig-viewer-role
rules:
- apiGroups:
  - dpu.openshift.io
  resources:
  - ovnkubeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dpu.openshift.io
  resources:
  - ovnkubeconfigs/status
  verbs:
  - get
