
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dpu.openshift.io
  resources:
  - ovnkubeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dpu.openshift.io
  resources:
  - ovnkubeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - dpu.openshift.io
  resources:
  - ovnkubeconfigs/status
  verbs:
  - get
  - patch
  - update
